-- AlterTable
ALTER TABLE "Complex" ADD COLUMN     "closeAt" TEXT NOT NULL DEFAULT '00:00',
ADD COLUMN     "images" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "openAt" TEXT NOT NULL DEFAULT '08:00',
ADD COLUMN     "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "description" DROP NOT NULL;
